// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using com.brettnamba.DotSync.FileSystem.Infrastructure.FileStorage.EntityFrameworkCore;

#nullable disable

namespace com.brettnamba.DotSync.FileSystem.Infrastructure.FileStorage.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(FileStorageDbContext))]
    [Migration("20240616093304_InitialCreateFileStorage")]
    partial class InitialCreateFileStorage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("file_storage")
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("com.brettnamba.DotSync.FileSystem.Domain.FileStorage.Entities.DotFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("FileCreation")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("file_creation")
                        .HasColumnOrder(4);

                    b.Property<DateTimeOffset>("FirstSync")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_sync")
                        .HasColumnOrder(7);

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_verified")
                        .HasColumnOrder(5);

                    b.Property<DateTimeOffset>("LastSync")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_sync")
                        .HasColumnOrder(6);

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("path")
                        .HasColumnOrder(1);

                    b.Property<string>("Sha256Checksum")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sha256_checksum")
                        .HasColumnOrder(2);

                    b.Property<long>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("size")
                        .HasColumnOrder(3);

                    b.HasKey("Id")
                        .HasName("files_pkey");

                    b.HasIndex(new[] { "Path" }, "files_path_idx")
                        .IsUnique();

                    b.HasIndex(new[] { "Sha256Checksum" }, "files_sha256_checksum_idx")
                        .IsUnique();

                    b.ToTable("files", "file_storage");
                });

            modelBuilder.Entity("com.brettnamba.DotSync.FileSystem.Domain.FileStorage.Entities.StorageLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("path")
                        .HasColumnOrder(2);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(12)")
                        .HasColumnName("type")
                        .HasColumnOrder(1);

                    b.ComplexProperty<Dictionary<string, object>>("StorageStatistics", "com.brettnamba.DotSync.FileSystem.Domain.FileStorage.Entities.StorageLocation.StorageStatistics#StorageStatistics", b1 =>
                        {
                            b1.Property<long>("FileCount")
                                .HasColumnType("bigint")
                                .HasColumnName("file_count")
                                .HasColumnOrder(3);

                            b1.Property<long>("Size")
                                .HasColumnType("bigint")
                                .HasColumnName("size")
                                .HasColumnOrder(4);
                        });

                    b.HasKey("Id")
                        .HasName("storage_locations_pkey");

                    b.HasIndex(new[] { "Path" }, "storage_locations_path_idx")
                        .IsUnique();

                    b.ToTable("storage_locations", "file_storage");
                });

            modelBuilder.Entity("com.brettnamba.DotSync.FileSystem.Domain.FileStorage.Entities.StoredFile", b =>
                {
                    b.Property<Guid>("file_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("storage_location_id")
                        .HasColumnType("uuid");

                    b.HasKey("file_id", "storage_location_id");

                    b.HasIndex("storage_location_id");

                    b.ToTable("stored_files", "file_storage");
                });

            modelBuilder.Entity("com.brettnamba.DotSync.FileSystem.Domain.FileStorage.ValueObjects.HistoricalStorageStatistics", b =>
                {
                    b.Property<Guid>("storage_location_id")
                        .HasColumnType("uuid")
                        .HasColumnOrder(0);

                    b.Property<DateTimeOffset>("DateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp")
                        .HasColumnOrder(1);

                    b.ComplexProperty<Dictionary<string, object>>("Statistics", "com.brettnamba.DotSync.FileSystem.Domain.FileStorage.ValueObjects.HistoricalStorageStatistics.Statistics#StorageStatistics", b1 =>
                        {
                            b1.Property<long>("FileCount")
                                .HasColumnType("bigint")
                                .HasColumnName("file_count")
                                .HasColumnOrder(2);

                            b1.Property<long>("Size")
                                .HasColumnType("bigint")
                                .HasColumnName("size")
                                .HasColumnOrder(3);
                        });

                    b.HasKey("storage_location_id", "DateTime")
                        .HasName("historical_storage_statistics_pkey");

                    b.ToTable("historical_storage_statistics", "file_storage");
                });

            modelBuilder.Entity("com.brettnamba.DotSync.FileSystem.Domain.FileStorage.Entities.StoredFile", b =>
                {
                    b.HasOne("com.brettnamba.DotSync.FileSystem.Domain.FileStorage.Entities.DotFile", null)
                        .WithMany()
                        .HasForeignKey("file_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("com.brettnamba.DotSync.FileSystem.Domain.FileStorage.Entities.StorageLocation", null)
                        .WithMany()
                        .HasForeignKey("storage_location_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("com.brettnamba.DotSync.FileSystem.Domain.FileStorage.ValueObjects.HistoricalStorageStatistics", b =>
                {
                    b.HasOne("com.brettnamba.DotSync.FileSystem.Domain.FileStorage.Entities.StorageLocation", null)
                        .WithMany("HistoricalStorageStatistics")
                        .HasForeignKey("storage_location_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("historical_storage_statistics_storage_locations_id_fkey");
                });

            modelBuilder.Entity("com.brettnamba.DotSync.FileSystem.Domain.FileStorage.Entities.StorageLocation", b =>
                {
                    b.Navigation("HistoricalStorageStatistics");
                });
#pragma warning restore 612, 618
        }
    }
}
