// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using com.brettnamba.DotSync.FileSystem.Infrastructure.FileSystems.EntityFrameworkCore;

#nullable disable

namespace com.brettnamba.DotSync.FileSystem.Infrastructure.FileSystems.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(FileSystemsDbContext))]
    [Migration("20260125100441_RemoveFileIsVerified")]
    partial class RemoveFileIsVerified
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("file_systems")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("com.brettnamba.DotSync.FileSystem.Domain.FileSystems.Entities.DotFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("FileCreation")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("file_creation")
                        .HasColumnOrder(4);

                    b.Property<DateTimeOffset>("FirstSync")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_sync")
                        .HasColumnOrder(6);

                    b.Property<DateTimeOffset>("LastSync")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_sync")
                        .HasColumnOrder(5);

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("path")
                        .HasColumnOrder(1);

                    b.Property<string>("Sha256Checksum")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sha256_checksum")
                        .HasColumnOrder(2);

                    b.Property<long>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("size")
                        .HasColumnOrder(3);

                    b.HasKey("Id")
                        .HasName("files_pkey");

                    b.HasIndex(new[] { "Path" }, "files_path_idx")
                        .IsUnique();

                    b.HasIndex(new[] { "Sha256Checksum" }, "files_sha256_checksum_idx")
                        .IsUnique();

                    b.ToTable("files", "file_systems");
                });

            modelBuilder.Entity("com.brettnamba.DotSync.FileSystem.Domain.FileSystems.Entities.StorageLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("path")
                        .HasColumnOrder(2);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(12)")
                        .HasColumnName("type")
                        .HasColumnOrder(1);

                    b.HasKey("Id")
                        .HasName("storage_locations_pkey");

                    b.HasIndex(new[] { "Path" }, "storage_locations_path_idx")
                        .IsUnique();

                    b.ToTable("storage_locations", "file_systems");
                });

            modelBuilder.Entity("com.brettnamba.DotSync.FileSystem.Domain.FileSystems.Entities.SyncedFile", b =>
                {
                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_id")
                        .HasColumnOrder(0);

                    b.Property<Guid>("StorageLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("storage_location_id")
                        .HasColumnOrder(1);

                    b.Property<DateTimeOffset>("LastSync")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_sync")
                        .HasColumnOrder(2);

                    b.HasKey("FileId", "StorageLocationId")
                        .HasName("synced_files_pkey");

                    b.HasIndex(new[] { "StorageLocationId" }, "synced_files_storage_location_id_idx");

                    b.ToTable("synced_files", "file_systems");
                });

            modelBuilder.Entity("com.brettnamba.DotSync.FileSystem.Domain.FileSystems.Entities.SyncedFile", b =>
                {
                    b.HasOne("com.brettnamba.DotSync.FileSystem.Domain.FileSystems.Entities.DotFile", "File")
                        .WithMany("SyncedFiles")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("synced_files_files_id_fkey");

                    b.HasOne("com.brettnamba.DotSync.FileSystem.Domain.FileSystems.Entities.StorageLocation", "StorageLocation")
                        .WithMany("SyncedFiles")
                        .HasForeignKey("StorageLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("synced_files_storage_locations_id_fkey");

                    b.Navigation("File");

                    b.Navigation("StorageLocation");
                });

            modelBuilder.Entity("com.brettnamba.DotSync.FileSystem.Domain.FileSystems.Entities.DotFile", b =>
                {
                    b.Navigation("SyncedFiles");
                });

            modelBuilder.Entity("com.brettnamba.DotSync.FileSystem.Domain.FileSystems.Entities.StorageLocation", b =>
                {
                    b.Navigation("SyncedFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
