// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using com.brettnamba.DotSync.FileSystem.Infrastructure.StorageLocations.EntityFrameworkCore;

#nullable disable

namespace com.brettnamba.DotSync.FileSystem.Infrastructure.StorageLocations.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(StorageLocationsDbContext))]
    [Migration("20240423223213_InitialCreateStorageLocations")]
    partial class InitialCreateStorageLocations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("storage_locations")
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("com.brettnamba.DotSync.FileSystem.Domain.StorageLocations.Entities.StorageLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("path")
                        .HasColumnOrder(2);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(12)")
                        .HasColumnName("type")
                        .HasColumnOrder(1);

                    b.ComplexProperty<Dictionary<string, object>>("StorageStatistics", "com.brettnamba.DotSync.FileSystem.Domain.StorageLocations.Entities.StorageLocation.StorageStatistics#StorageStatistics", b1 =>
                        {
                            b1.Property<long>("FileCount")
                                .HasColumnType("bigint")
                                .HasColumnName("file_count")
                                .HasColumnOrder(3);

                            b1.Property<long>("Size")
                                .HasColumnType("bigint")
                                .HasColumnName("size")
                                .HasColumnOrder(4);
                        });

                    b.HasKey("Id")
                        .HasName("storage_locations_pkey");

                    b.HasIndex(new[] { "Path" }, "storage_locations_path_idx")
                        .IsUnique();

                    b.ToTable("storage_locations", "storage_locations");
                });

            modelBuilder.Entity("com.brettnamba.DotSync.FileSystem.Domain.StorageLocations.ValueObjects.HistoricalStorageStatistics", b =>
                {
                    b.Property<Guid>("storage_location_id")
                        .HasColumnType("uuid")
                        .HasColumnOrder(0);

                    b.Property<DateTimeOffset>("DateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp")
                        .HasColumnOrder(1);

                    b.ComplexProperty<Dictionary<string, object>>("Statistics", "com.brettnamba.DotSync.FileSystem.Domain.StorageLocations.ValueObjects.HistoricalStorageStatistics.Statistics#StorageStatistics", b1 =>
                        {
                            b1.Property<long>("FileCount")
                                .HasColumnType("bigint")
                                .HasColumnName("file_count")
                                .HasColumnOrder(2);

                            b1.Property<long>("Size")
                                .HasColumnType("bigint")
                                .HasColumnName("size")
                                .HasColumnOrder(3);
                        });

                    b.HasKey("storage_location_id", "DateTime")
                        .HasName("historical_storage_statistics_pkey");

                    b.ToTable("historical_storage_statistics", "storage_locations");
                });

            modelBuilder.Entity("com.brettnamba.DotSync.FileSystem.Domain.StorageLocations.ValueObjects.HistoricalStorageStatistics", b =>
                {
                    b.HasOne("com.brettnamba.DotSync.FileSystem.Domain.StorageLocations.Entities.StorageLocation", null)
                        .WithMany("HistoricalStorageStatistics")
                        .HasForeignKey("storage_location_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("historical_storage_statistics_storage_locations_id_fkey");
                });

            modelBuilder.Entity("com.brettnamba.DotSync.FileSystem.Domain.StorageLocations.Entities.StorageLocation", b =>
                {
                    b.Navigation("HistoricalStorageStatistics");
                });
#pragma warning restore 612, 618
        }
    }
}
