<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <UserSecretsId>617ffdc4-69c0-4ce7-b176-b9fb4013686c</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
      <Content Include="..\..\..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\FileSystem\DotSync.FileSystem.Infrastructure\DotSync.FileSystem.Infrastructure.csproj" />
      <ProjectReference Include="..\DotSync.Apps.Common\DotSync.Apps.Common.csproj" />
    </ItemGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="Components\Layout\MainLayout.razor" />
      <_ContentIncludedByDefault Remove="Components\Pages\Error.razor" />
      <_ContentIncludedByDefault Remove="Components\Pages\Home.razor" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="MudBlazor" Version="8.15.0" />
    </ItemGroup>

</Project>
