<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>com.brettnamba.DotSync.Common.Infrastructure</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\DotSync.Common.Application\DotSync.Common.Application.csproj" />
    </ItemGroup>

</Project>
